CC = g++
CFLAGS = -g -Iinclude 
FILES = ./src/ParamChecks.cpp ./src/NetScanner.cpp ./src/main.cpp

all: networkscanner

networkscanner: 
	${CC} ${FILES} ${CFLAGS} -o networkscanner
	
clean: 
	rm networkscanner
